FROM alpine:3.12
USER root
ARG PPM_CONFIG_FILE
ARG PPM_MAP_FILE

WORKDIR /cvdi-stream

ENV DEBIAN_FRONTEND=noninteractive

# update the package manager
RUN apk update

# add build tools
RUN apk add --upgrade --no-cache --virtual .build-deps \
    build-base \
    cmake \
    git \
    wget \
    gcc \
    g++ \
    linux-headers \
    make \
    musl-dev \
    openssl-dev \
    protobuf-dev \
    protobuf-c-dev \
    sudo \
    bash

# add librdkafka from edge branch
RUN sed -i -e 's/v3\.4/edge/g' /etc/apk/repositories \
    && apk upgrade --update-cache --available \
    && apk add --no-cache librdkafka librdkafka-dev

# add the source and build files
ADD CMakeLists.txt /cvdi-stream
ADD ./src /cvdi-stream/src
ADD ./cv-lib /cvdi-stream/cv-lib
ADD ./include /cvdi-stream/include
ADD ./kafka-test /cvdi-stream/kafka-test
ADD ./unit-test-data /cvdi-stream/unit-test-data
ADD config/${PPM_CONFIG_FILE} /cvdi-stream/config/
ADD data/${PPM_MAP_FILE} /cvdi-stream/config/
ADD ./config /cvdi-stream/config

# do the build
RUN export LD_LIBRARY_PATH=/usr/local/lib && mkdir /cvdi-stream-build && cd /cvdi-stream-build && cmake /cvdi-stream && make

# add test data (this changes frequently so keep it low in the file)
ADD ./docker-test /cvdi-stream/docker-test

# run the tool
CMD ["/cvdi-stream/docker-test/ppm-nsv.sh"]
