name: DockerHub Build and Push

on:
  push:
    branches: [ master, develop, release/*]
    tags:     [ "*" ] 
  workflow_dispatch:

jobs:
  publish:
    if: github.event.pull_request.base.repo.owner.login == 'usdot-jpo-ode'
    uses: usdot-jpo-ode/actions/.github/workflows/dockerhub.yml@main
    with:
      image: usdotjpoode/jpo-cvdp
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:   ${{ secrets.DOCKERHUB_TOKEN }}
